### ISSUE TITLE
Namespace should match the gem name

### ISSUE THREAD

**Issue by estebanz01** [estebanz01/ruby-statistics#10]
Per this thread: https://www.reddit.com/r/ruby/comments/76vse9/rubystatistics_a_gem_for_statistical_methods_and/

It's important to have a match between the gem name and the global namespace defined. I tried to move it, but It broke all my specs and the paths didn't load as desired.

**Comment by pboling** [comment]
Related to this issie, in the readme, the gem is `ruby-statistics`, but the readme says under "Basic Usage":

> just require the `statistics` gem in order to load it

What is the statistics gem?

**Comment by estebanz01** [comment]
Hola @pboling ! that's not a gem, but the name of a namespace defined here: https://github.com/estebanz01/ruby-statistics/blob/master/lib/statistics.rb

This issue is specifically to address the mismatch: `ruby-statistics` gem should use a namespace of `RubyStatistics` instead of `Statistics`.

the readme and the examples in the wiki, is telling you that if you `require 'statistics'`, then you can use the gem as expected.

Hope it helps!

**Comment by pboling** [comment]
> that's not a gem, but the name of a namespace defined here

Right, I mentioned it because the README says it is a gem, and it isn't.  Very confusing.

I figured out that it should be added like this to a project using a Gemfile:
```ruby
gem 'ruby-statistics`, require: 'statistics'
```

That's probably what the readme should say.

**Comment by estebanz01** [comment]
well, that requires the gem in the entire project, sometimes you don't want that, you might want to use only the distributions or only an specific class.

Thanks for the feedback. I'll try to come up with better wording for the README.

**Comment by estebanz01** [comment]
Resolved in #120
