### ISSUE TITLE
Crystal programming support

### ISSUE THREAD

**Issue by proyb6** [estebanz01/ruby-statistics#29]
It would be easy and better if you can extend this libraries to Crystal programming language to get free performance boost and lower memory consumption.

**Comment by proyb6** [comment]
Sure https://crystal-lang.org/

**Comment by estebanz01** [comment]
I think I misunderstood your suggestion. I think this is out of scope of my plans for this gem, but forks and PRs are always welcome. Thanks for posting this issue !
