### ISSUE TITLE
Weibull random number generator with skewness and kurtosis parameters

### ISSUE THREAD

**Issue by joshm1204** [estebanz01/ruby-statistics#31]
Is there a way to add skewness and kurtosis parameters to a Weibull number generator?

https://github.com/estebanz01/ruby-statistics/blob/master/lib/statistics/distribution/weibull.rb

**Comment by estebanz01** [comment]
hey! question: how would you expect to use the skewness and kurtosis for the number generator? Because those two properties are generated based on the scale and shape parameters.
