### ISSUE TITLE
Standard Deviation

### ISSUE THREAD

**Issue by lflucasferreira** [estebanz01/ruby-statistics#39]
Excuse me but I would like to know if there is a function for the Standard Deviation. I was looking into the wiki and did not find it.

Thank you in advance.

**Comment by estebanz01** [comment]
@lflucasferreira do you want the standard deviation of an Enumerable ? In that case, you can use this: https://github.com/estebanz01/ruby-statistics/blob/master/lib/enumerable.rb#L2
